-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.inventario_alerta
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    mensaje text COLLATE pg_catalog."default" NOT NULL,
    insumo_id bigint NOT NULL,
    CONSTRAINT inventario_alerta_pkey PRIMARY KEY (id),
    CONSTRAINT inventario_alerta_insumo_id_tipo_3214819e_uniq UNIQUE (insumo_id, tipo)
);

CREATE TABLE IF NOT EXISTS public.inventario_area
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT inventario_area_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventario_categoria
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT inventario_categoria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventario_compra
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha date NOT NULL,
    total numeric(10, 2) NOT NULL,
    proveedor_id bigint NOT NULL,
    usuario_id integer NOT NULL,
    CONSTRAINT inventario_compra_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventario_consumo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cantidad integer NOT NULL,
    fecha date NOT NULL,
    insumo_id bigint NOT NULL,
    usuario_id integer NOT NULL,
    CONSTRAINT inventario_consumo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventario_detallecompra
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cantidad integer NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    compra_id bigint NOT NULL,
    insumo_id bigint NOT NULL,
    CONSTRAINT inventario_detallecompra_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventario_insumo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    unidad_medida character varying(50) COLLATE pg_catalog."default" NOT NULL,
    stock_minimo integer NOT NULL,
    stock_actual integer NOT NULL,
    area_id bigint NOT NULL,
    categoria_id bigint NOT NULL,
    CONSTRAINT inventario_insumo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventario_lote
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero_lote character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cantidad integer NOT NULL,
    fecha_vencimiento date NOT NULL,
    insumo_id bigint NOT NULL,
    CONSTRAINT inventario_lote_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventario_movimiento
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tipo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    cantidad integer NOT NULL,
    fecha timestamp with time zone NOT NULL,
    insumo_id bigint NOT NULL,
    usuario_id integer,
    lote_id bigint,
    CONSTRAINT inventario_movimiento_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventario_prediccion
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    consumo_estimado integer NOT NULL,
    fecha date NOT NULL,
    insumo_id bigint NOT NULL,
    accion character varying(100) COLLATE pg_catalog."default",
    dias_restantes double precision,
    score double precision,
    stock_actual double precision,
    CONSTRAINT inventario_prediccion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventario_proveedor
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(254) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT inventario_proveedor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios_perfil
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    telefono character varying(20) COLLATE pg_catalog."default" NOT NULL,
    rut character varying(20) COLLATE pg_catalog."default" NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT usuarios_perfil_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_perfil_user_id_key UNIQUE (user_id)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.inventario_alerta
    ADD CONSTRAINT inventario_alerta_insumo_id_6fb14070_fk FOREIGN KEY (insumo_id)
    REFERENCES public.inventario_insumo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_alerta_insumo_id_6fb14070
    ON public.inventario_alerta(insumo_id);


ALTER TABLE IF EXISTS public.inventario_compra
    ADD CONSTRAINT inventario_compra_proveedor_id_085e6477_fk FOREIGN KEY (proveedor_id)
    REFERENCES public.inventario_proveedor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_compra_proveedor_id_085e6477
    ON public.inventario_compra(proveedor_id);


ALTER TABLE IF EXISTS public.inventario_compra
    ADD CONSTRAINT inventario_compra_usuario_id_c3062858_fk_auth_user_id FOREIGN KEY (usuario_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_compra_usuario_id_c3062858
    ON public.inventario_compra(usuario_id);


ALTER TABLE IF EXISTS public.inventario_consumo
    ADD CONSTRAINT inventario_consumo_insumo_id_e75c0cd0_fk FOREIGN KEY (insumo_id)
    REFERENCES public.inventario_insumo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_consumo_insumo_id_e75c0cd0
    ON public.inventario_consumo(insumo_id);


ALTER TABLE IF EXISTS public.inventario_consumo
    ADD CONSTRAINT inventario_consumo_usuario_id_7bcf2bfa_fk_auth_user_id FOREIGN KEY (usuario_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_consumo_usuario_id_7bcf2bfa
    ON public.inventario_consumo(usuario_id);


ALTER TABLE IF EXISTS public.inventario_detallecompra
    ADD CONSTRAINT inventario_detallecompra_compra_id_bf08cac8_fk FOREIGN KEY (compra_id)
    REFERENCES public.inventario_compra (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_detallecompra_compra_id_bf08cac8
    ON public.inventario_detallecompra(compra_id);


ALTER TABLE IF EXISTS public.inventario_detallecompra
    ADD CONSTRAINT inventario_detallecompra_insumo_id_05991524_fk FOREIGN KEY (insumo_id)
    REFERENCES public.inventario_insumo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_detallecompra_insumo_id_05991524
    ON public.inventario_detallecompra(insumo_id);


ALTER TABLE IF EXISTS public.inventario_insumo
    ADD CONSTRAINT inventario_insumo_area_id_3defd8d3_fk FOREIGN KEY (area_id)
    REFERENCES public.inventario_area (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_insumo_area_id_3defd8d3
    ON public.inventario_insumo(area_id);


ALTER TABLE IF EXISTS public.inventario_insumo
    ADD CONSTRAINT inventario_insumo_categoria_id_29271d54_fk FOREIGN KEY (categoria_id)
    REFERENCES public.inventario_categoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_insumo_categoria_id_29271d54
    ON public.inventario_insumo(categoria_id);


ALTER TABLE IF EXISTS public.inventario_lote
    ADD CONSTRAINT inventario_lote_insumo_id_bcc4d763_fk FOREIGN KEY (insumo_id)
    REFERENCES public.inventario_insumo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_lote_insumo_id_bcc4d763
    ON public.inventario_lote(insumo_id);


ALTER TABLE IF EXISTS public.inventario_movimiento
    ADD CONSTRAINT inventario_movimiento_insumo_id_0b8be08c_fk FOREIGN KEY (insumo_id)
    REFERENCES public.inventario_insumo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_movimiento_insumo_id_0b8be08c
    ON public.inventario_movimiento(insumo_id);


ALTER TABLE IF EXISTS public.inventario_movimiento
    ADD CONSTRAINT inventario_movimiento_lote_id_f2a80ab8_fk_inventario_lote_id FOREIGN KEY (lote_id)
    REFERENCES public.inventario_lote (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_movimiento_lote_id_f2a80ab8
    ON public.inventario_movimiento(lote_id);


ALTER TABLE IF EXISTS public.inventario_movimiento
    ADD CONSTRAINT inventario_movimiento_usuario_id_f452f794_fk_auth_user_id FOREIGN KEY (usuario_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_movimiento_usuario_id_f452f794
    ON public.inventario_movimiento(usuario_id);


ALTER TABLE IF EXISTS public.inventario_prediccion
    ADD CONSTRAINT inventario_prediccion_insumo_id_44d4537c_fk FOREIGN KEY (insumo_id)
    REFERENCES public.inventario_insumo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventario_prediccion_insumo_id_44d4537c
    ON public.inventario_prediccion(insumo_id);


ALTER TABLE IF EXISTS public.usuarios_perfil
    ADD CONSTRAINT usuarios_perfil_user_id_f343affd_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS usuarios_perfil_user_id_key
    ON public.usuarios_perfil(user_id);

END;