# Generated by Django 4.1 on 2026-03-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_compra_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='alerta',
            unique_together={('insumo', 'tipo')},
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='fecha',
        ),
    ]
