# Generated by Django 4.1 on 2026-03-31 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_alerta_tipo_alter_alerta_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.lote'),
        ),
    ]
