# Generated by Django 4.1 on 2026-04-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_movimiento_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccion',
            name='accion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='dias_restantes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='stock_actual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
