# Generated by Django 4.1 on 2026-04-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_prediccion_accion_prediccion_dias_restantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
