# Generated by Django 4.1 on 2026-04-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_solicitud_detallesolicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='area',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='solicitante',
        ),
        migrations.DeleteModel(
            name='DetalleSolicitud',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
        migrations.AddField(
            model_name='insumo',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.subcategoria'),
        ),
    ]
