# Generated by Django 4.1 on 2026-04-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_subcategoria_remove_solicitud_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='subcategoria',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
