# Generated by Django 4.1 on 2026-04-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_compra_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
