# Generated by Django 6.0.3 on 2026-06-29 23:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación')),
                ('responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('estado', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodega',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='nexofaena.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EntregaEPP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('firma_base64', models.TextField(blank=True, null=True, verbose_name='Firma Digital')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='nexofaena.bodega', verbose_name='Bodega de Origen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Bodeguero/Supervisor')),
            ],
            options={
                'verbose_name': 'Entrega EPP',
                'verbose_name_plural': 'Entregas EPP',
                'db_table': 'entrega_epp',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción técnica')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('unidad_medida', models.CharField(default='UN', max_length=20, verbose_name='Unidad de Medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Stock Máximo')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Física (Rack/Pasillo)')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='nexofaena.bodega', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntregaEPP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Entregada')),
                ('talla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Talla')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones del Ítem')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nexofaena.entregaepp')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nexofaena.inventario', verbose_name='Producto en Inventario')),
            ],
            options={
                'verbose_name': 'Detalle Entrega EPP',
                'verbose_name_plural': 'Detalles Entrega EPP',
                'db_table': 'detalle_entrega_epp',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo'), ('STOCK_CRITICO', 'Stock Crítico'), ('VENCIMIENTO', 'Vencimiento'), ('SISTEMA', 'Sistema')], db_index=True, default='SISTEMA', max_length=30, verbose_name='Tipo de alerta')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='nexofaena.bodega', verbose_name='Bodega')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='nexofaena.inventario', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerta',
                'ordering': ['-fecha_alerta'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT Trabajador')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo / Especialidad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo en Faena?')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'trabajadores',
                'indexes': [models.Index(fields=['rut'], name='trabajadore_rut_37bdf4_idx'), models.Index(fields=['apellido_paterno', 'nombres'], name='trabajadore_apellid_3a8001_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock Antes')),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock Después')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nexofaena.bodega', verbose_name='Bodega')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='nexofaena.entregaepp', verbose_name='Entrega Asociada')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nexofaena.inventario', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexofaena.trabajador', verbose_name='Trabajador Recibió')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='entregaepp',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_epp', to='nexofaena.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['codigo', 'nombre'], name='inventario_codigo_364819_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['bodega'], name='inventario_bodega__9b371f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['estado'], name='inventario_estado_09f7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha', 'tipo_movimiento'], name='movimiento__fecha_9b95b9_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['inventario', 'bodega'], name='movimiento__inventa_c6ccb6_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaepp',
            index=models.Index(fields=['fecha_entrega', 'estado'], name='entrega_epp_fecha_e_c4c99f_idx'),
        ),
    ]
