# Generated by Django 6.0.3 on 2026-07-01 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Invitación de Registro',
                'verbose_name_plural': 'Invitaciones de Registro',
                'db_table': 'invitacion_registro',
            },
        ),
    ]
