# Generated by Django 6.0.3 on 2026-07-02 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0002_invitacionregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaInventario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_inventario', to='nexofaena.bodega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_inventario',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAuditoriaInventario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_sistema', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_fisico', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nexofaena.auditoriainventario')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nexofaena.inventario')),
            ],
            options={
                'db_table': 'detalle_auditoria_inventario',
            },
        ),
    ]
