# Generated by Django 6.0.3 on 2026-06-13 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0002_bodega_inventario_movimientoinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'EPP',
                'verbose_name_plural': 'EPPs',
                'db_table': 'epp',
            },
        ),
        migrations.CreateModel(
            name='EntregaEPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('firma_base64', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_epp', to='nexofaena.trabajador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega EPP',
                'verbose_name_plural': 'Entregas EPP',
                'db_table': 'entrega_epp',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntregaEPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('talla', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nexofaena.entregaepp')),
                ('epp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nexofaena.epp')),
            ],
            options={
                'verbose_name': 'Detalle Entrega EPP',
                'verbose_name_plural': 'Detalles Entrega EPP',
                'db_table': 'detalle_entrega_epp',
            },
        ),
    ]
