# Generated by Django 6.0.3 on 2026-08-26 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0003_auditoriainventario_detalleauditoriainventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='detalle_entrega',
            field=models.ForeignKey(blank=True, help_text='Vincula la alerta de vencimiento con la entrega específica que la originó.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='nexofaena.detalleentregaepp', verbose_name='Entrega Asociada'),
        ),
        migrations.AddField(
            model_name='detalleentregaepp',
            name='devuelto',
            field=models.BooleanField(default=False, verbose_name='¿Devuelto?'),
        ),
        migrations.AddField(
            model_name='detalleentregaepp',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución'),
        ),
        migrations.AddField(
            model_name='detalleentregaepp',
            name='fecha_vencimiento_vida_util',
            field=models.DateField(blank=True, help_text='Calculado automáticamente al entregar según la vida útil del producto.', null=True, verbose_name='Vencimiento vida útil'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='es_devolutivo',
            field=models.BooleanField(default=False, help_text='Ej. radios de comunicación: se entregan al inicio del turno y deben devolverse al final.', verbose_name='¿Es un activo devolutivo?'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tiempo_reposicion_dias',
            field=models.PositiveIntegerField(default=7, help_text='Días estimados que demora el proveedor en reponer stock una vez generado el pedido.', verbose_name='Tiempo de Reposición (días)'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='vida_util_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Días de uso permitidos antes de exigir recambio (ej. 365 para cascos/zapatos). Vacío = sin control de vencimiento.', null=True, verbose_name='Vida Útil (días)'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo_alerta',
            field=models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo'), ('STOCK_CRITICO', 'Stock Crítico'), ('VENCIMIENTO', 'Vencimiento'), ('ANOMALIA_CONSUMO', 'Anomalía de Consumo'), ('SISTEMA', 'Sistema')], db_index=True, default='SISTEMA', max_length=30, verbose_name='Tipo de alerta'),
        ),
    ]
