# Generated by Django 6.0.3 on 2026-06-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0003_epp_entregaepp_detalleentregaepp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo'), ('STOCK_CRITICO', 'Stock Crítico'), ('VENCIMIENTO_EPP', 'Vencimiento EPP'), ('SISTEMA', 'Sistema')], max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nexofaena.bodega')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nexofaena.inventario')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerta',
            },
        ),
    ]
