# Generated by Django 6.0.3 on 2026-08-26 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0004_alerta_detalle_entrega_detalleentregaepp_devuelto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Unidad')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible en bodega'), ('ENTREGADA', 'Entregada'), ('DE_BAJA', 'De baja')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='nexofaena.inventario', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Unidad de Activo',
                'verbose_name_plural': 'Unidades de Activo',
                'db_table': 'unidad_activo',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='detalleentregaepp',
            name='unidad_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_detalle', to='nexofaena.unidadactivo', verbose_name='Unidad Entregada'),
        ),
        migrations.AddIndex(
            model_name='unidadactivo',
            index=models.Index(fields=['inventario', 'estado'], name='unidad_acti_inventa_8a4f99_idx'),
        ),
    ]
