# Generated by Django 6.0.3 on 2026-08-28 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0005_unidadactivo_detalleentregaepp_unidad_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriainventario',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por'),
        ),
        migrations.AddField(
            model_name='auditoriainventario',
            name='firma_autorizacion',
            field=models.TextField(blank=True, help_text='Firma digital (base64) del supervisor que autorizó un ajuste con descuadre crítico.', null=True, verbose_name='Firma de Autorización'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='es_activo_critico',
            field=models.BooleanField(default=False, help_text='Si un conteo cíclico detecta faltante en este producto, se exige firma de autorización de un supervisor para ajustar el stock.', verbose_name='¿Activo crítico / de alto valor?'),
        ),
    ]
