# Generated by Django 6.0.3 on 2026-08-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0006_auditoriainventario_autorizado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentregaepp',
            name='estado_devolucion',
            field=models.CharField(blank=True, choices=[('OPERATIVA', 'Operativa'), ('DAÑADA', 'Dañada')], help_text='Condición reportada por el pañolero al recibir de vuelta el activo devolutivo.', max_length=20, null=True, verbose_name='Estado al Devolver'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='es_despacho_rapido',
            field=models.BooleanField(default=False, help_text='Consumibles de alta rotación (ej. agua) que se descuentan con un clic, sin RUT ni firma, y quedan fuera de las alertas de anomalía de consumo.', verbose_name='¿Despacho rápido?'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo_alerta',
            field=models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo'), ('STOCK_CRITICO', 'Stock Crítico'), ('VENCIMIENTO', 'Vencimiento'), ('ANOMALIA_CONSUMO', 'Anomalía de Consumo'), ('MANTENIMIENTO', 'Mantenimiento'), ('CIERRE_TURNO', 'Cierre de Turno'), ('SISTEMA', 'Sistema')], db_index=True, default='SISTEMA', max_length=30, verbose_name='Tipo de alerta'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='unidadactivo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible en bodega'), ('ENTREGADA', 'Entregada'), ('EN_MANTENCION', 'En mantención'), ('DE_BAJA', 'De baja')], default='DISPONIBLE', max_length=20, verbose_name='Estado'),
        ),
    ]
