# Generated by Django 6.0.3 on 2026-09-05 20:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0007_detalleentregaepp_estado_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentregaepp',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Precio Unitario al Entregar (CLP)'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='clasificacion_5s',
            field=models.CharField(blank=True, choices=[('SEIRI', 'Seiri - Clasificar'), ('SEITON', 'Seiton - Ordenar'), ('SEISO', 'Seiso - Limpiar'), ('SEIKETSU', 'Seiketsu - Estandarizar'), ('SHITSUKE', 'Shitsuke - Disciplina')], help_text='Etapa de la metodología 5S asignada a este ítem/ubicación, usada como filtro de inventario.', max_length=20, null=True, verbose_name='Clasificación 5S'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio real de costo/reposición por unidad. Se usa para valorizar el stock y las entregas de pañol.', max_digits=12, verbose_name='Precio Unitario (CLP)'),
        ),
    ]
