# Generated by Django 6.0.3 on 2026-09-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0008_detalleentregaepp_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepp',
            name='turno',
            field=models.CharField(blank=True, choices=[('dia', 'Día'), ('noche', 'Noche')], editable=False, help_text='Calculado automáticamente desde la hora de entrega (umbral configurable en settings).', max_length=10, verbose_name='Turno'),
        ),
        migrations.AddIndex(
            model_name='entregaepp',
            index=models.Index(fields=['turno'], name='entrega_epp_turno_072c61_idx'),
        ),
    ]
