# Generated by Django 6.0.3 on 2026-09-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0009_entregaepp_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='unidades_por_pack',
            field=models.PositiveIntegerField(default=1, help_text='Para despacho rápido: cuántas unidades trae el pack que realmente se lleva la cuadrilla (ej. 6 para un six-pack de agua). 1 = se despacha por unidad suelta.', verbose_name='Unidades por Pack'),
        ),
    ]
