# Generated by Django 6.0.3 on 2026-09-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0010_inventario_unidades_por_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriainventario',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('AJUSTADA', 'Ajustada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=20),
        ),
    ]
