# Generated by Django 6.0.3 on 2026-09-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0011_alter_auditoriainventario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código corto de la bodega (ej. BOD-CEN, BOD-RES).', max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CENTRAL', 'Central'), ('RESERVA', 'Reserva')], help_text='Central: atiende al trabajador día a día. Reserva: stock de respaldo y baja rotación.', max_length=20, null=True, verbose_name='Tipo de bodega'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='talla',
            field=models.CharField(blank=True, help_text='Solo para productos con variantes de talla (guantes, buzos, zapatos). Vacío si no aplica.', max_length=20, null=True, verbose_name='Talla'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_recibidos', to='nexofaena.bodega', verbose_name='Bodega Destino (traspaso)'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='inventario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_como_destino', to='nexofaena.inventario', verbose_name='Producto en bodega destino (traspaso)'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_actual_destino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Stock Después (destino)'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_anterior_destino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Stock Antes (destino)'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='turno',
            field=models.CharField(blank=True, choices=[('dia', 'Día'), ('noche', 'Noche')], help_text='Turno habitual del trabajador (día/noche). Distinto del turno calculado por hora en cada entrega.', max_length=10, null=True, verbose_name='Turno Asignado'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución'), ('TRASPASO', 'Traspaso entre bodegas')], max_length=20, verbose_name='Tipo'),
        ),
    ]
