# Generated by Django 6.0.3 on 2026-09-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0012_bodega_codigo_bodega_tipo_inventario_talla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='es_despacho_rapido',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='unidades_por_pack',
        ),
    ]
