# Generated by Django 6.0.3 on 2026-09-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0013_remove_despacho_rapido_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepp',
            name='geolocalizacion_capturada_en',
            field=models.DateTimeField(blank=True, help_text='Momento real de la captura GPS en el dispositivo (distinto de fecha_entrega si la entrega se sincronizó después, en modo offline).', null=True, verbose_name='Geolocalización capturada en'),
        ),
        migrations.AddField(
            model_name='entregaepp',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='entregaepp',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='entregaepp',
            name='precision_metros',
            field=models.FloatField(blank=True, help_text='Radio de incertidumbre reportado por el dispositivo (GPSPosition.coords.accuracy).', null=True, verbose_name='Precisión GPS (m)'),
        ),
    ]
