# Generated by Django 6.0.3 on 2026-09-18 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0014_entrega_geolocalizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramEstadoBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_update_id', models.BigIntegerField(default=0, verbose_name='Último update_id procesado')),
            ],
            options={
                'verbose_name': 'Estado del Bot de Telegram',
                'verbose_name_plural': 'Estado del Bot de Telegram',
                'db_table': 'telegram_estado_bot',
            },
        ),
        migrations.CreateModel(
            name='TelegramCodigoVinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True, verbose_name='Código')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('expira_en', models.DateTimeField(verbose_name='Expira en')),
                ('usado', models.BooleanField(default=False, verbose_name='¿Usado?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_codigos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario NexoFaena')),
            ],
            options={
                'verbose_name': 'Código de Vinculación Telegram',
                'verbose_name_plural': 'Códigos de Vinculación Telegram',
                'db_table': 'telegram_codigo_vinculacion',
            },
        ),
        migrations.CreateModel(
            name='TelegramVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID de Telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=64, null=True, verbose_name='@usuario de Telegram')),
                ('vinculado_en', models.DateTimeField(auto_now_add=True, verbose_name='Vinculado en')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_vinculo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario NexoFaena')),
            ],
            options={
                'verbose_name': 'Vínculo Telegram',
                'verbose_name_plural': 'Vínculos Telegram',
                'db_table': 'telegram_vinculo',
            },
        ),
    ]
