# Generated by Django 6.0.3 on 2026-09-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0015_telegram_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='face_descriptor',
            field=models.JSONField(blank=True, help_text='Vector de 128 números generado por face-api.js al enrolar el rostro en el kiosco. No es una imagen.', null=True, verbose_name='Descriptor facial'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='face_enrolado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rostro enrolado en'),
        ),
    ]
