# Generated by Django 6.0.3 on 2026-09-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0016_trabajador_face_descriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo_alerta',
            field=models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo'), ('STOCK_CRITICO', 'Stock Crítico'), ('VENCIMIENTO', 'Vencimiento'), ('ANOMALIA_CONSUMO', 'Anomalía de Consumo'), ('MANTENIMIENTO', 'Mantenimiento'), ('CIERRE_TURNO', 'Cierre de Turno'), ('SISTEMA', 'Sistema'), ('INTENTO_SUPLANTACION', 'Intento de Suplantación')], db_index=True, default='SISTEMA', max_length=30, verbose_name='Tipo de alerta'),
        ),
    ]
