# Generated by Django 6.0.3 on 2026-10-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexofaena', '0017_alter_alerta_tipo_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepp',
            name='canal',
            field=models.CharField(choices=[('BODEGA', 'Bodeguero (registro manual)'), ('KIOSCO', 'Kiosco (autoservicio)')], default='BODEGA', max_length=10, verbose_name='Canal'),
        ),
    ]
